config:
  device: 'cuda:3'
  # 环境参数
  env_name: 'multiparticles' 
  scenario_name: 'simple_adversary'
  max_episode_len: 25
  time_steps: 1000000    # 1e6
  random_steps: 500 
  gui: false
  evaluate: false
  continuous_actions: False
  # 训练通用参数
  epsilon: 0.2
  gamma: 0.95
  tau: 0.01
  batch_size: 256
  buffer_size: 500000
  use_priority: false
  use_normalize: false
  seed: 20
  anneal_lr: false
  torch_deterministic: False
  # 日志参数
  base_path: "results"
  save_rate: 20000  # 保存模型频率
  log_interval: 100
  save_interval: 2000  # 绘制损失频率
  save_vedio: False
  learn_interval: 10
  # 评估参数
  evaluate_episodes: 50
  evaluate_episode_len: 25
  evaluate: False
  evaluate_rate: 1000
  demo_length: 100
  # MPE环境参数
  num_good: 1
  num_adversaries: 1
  num_obstacles: 0
  num_food: 2
  num_forests: 2
  # 算法参数
  hidden_size: 100
	actor_lr: 5e-5
	critic_lr: 1e-5
	tau: 1e-5
	init_w: True
	gradperstep: 1.0
	gamma: 0.5
	batch_size: 512
	buffer_size: 100000
	reward_scaling: 10.0
  # 进化算法参数
  env_choice: 'rover_tight'
	popn_size: 10
  rollsize: 0
  is_matd3: false
  is_maddpg: false
  frames: 2
  crossover_prob: 0.1
	mutation_prob: 0.9
	extinction_prob: 0.005  # Probability of extinction event
	extinction_magnitude: 0.5  # Probabilty of extinction for each genome, given an extinction event
	weight_clamp: 1000000
	mut_distribution: 1  # 1-Gaussian, 2-Laplace, 3-Uniform
	num_elites: 4
  # 其他
	action_dim: 2
	num_test: 10
	test_gap: 5
