# -------algo-------
batch_size: 256
buffer_size: 500000
gamma: 0.95
use_priority: false
use_normalize: false
anneal_lr: false
epsilon: 0.2
tau: 0.01
use_public_buffer: True
lr_actor: 0.0001
lr_critic: 0.001
noise_rate: 0.1
exploration_decay: 0.9999
policy_noise: 0.2
noise_clip: 0.5
policy_freq: 2
ensemble_k: 2