# -------pursuit_evasion env-------
scenario_name: 'pursuit_evasion'
max_episode_len: 100
time_steps: 1000000    # 1e6
random_steps: 500 
gui: false
continuous_actions: false
num_good: 5
num_adversary: 1
num_obstacle: 10
num_goal: 2